apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-conf
  labels:
    name: chat-conf
data:
  env: |
    APP_PORT=3003
    MICRO_LIVE_GENERATOR_GRPC_URL=live-service-grpc:5000
    MICRO_LIVE_BOT_GRPC_URL=codebot-service:50051
  

    TYPEORM_CONNECTION=mysql
    TYPEORM_HOST=chat-mysql-service
    TYPEORM_USERNAME=root
    TYPEORM_PASSWORD=a1s2d3f4
    TYPEORM_DATABASE=micro_live_chat
    TYPEORM_PORT=3306
    TYPEORM_ENTITIES=src/**/*.entity.ts
    TYPEORM_MIGRATIONS=src/migrations/**/*.ts
    TYPEORM_MIGRATIONS_DIR=src/migrations
    
    REDIS_HOST=chat-redis-service
    REDIS_PORT=6379
    
    SOCKET_IO_ALLOW_ORIGINS=http://live.fullcycle.com.br:80
    
    RABBITMQ_HOST=rabbitmq-service
    RABBITMQ_USER=admin
    RABBITMQ_PASSWORD=admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: wesleywillians/maratona2-chat
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: chat-conf
          volumeMounts:
          - name: chat-conf
            subPath: .env
            mountPath: /home/node/app/.env

      volumes:
      - name: chat-conf
        configMap:
          name: chat-conf
          items:
            - key: env
              path: .env
          

---

apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
  selector:
    app: chat
    

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: chat-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 3003
      name: http
      protocol: HTTP
    hosts:  
    - "*"
---
  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chat-vs
spec:
  hosts:
  - "chat.live.fullcycle.com.br"
  gateways:
  - chat-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 3003
        host: chat-service